---
title: "Simulating Tissues with Oneiric"
author: "Patrick Martin"
output:
    pdf_document: null
    keep_tex: yes
    number_sections: no
    html_document:
        toc: true
package: '`oneiric'''
vignette: |
    %\VignetteIndexEntry{Oneiric User's Guide}
    %\VignetteEncoding{UTF-8}
    %\VignetteEngine{knitr::rmarkdown}
---

#  Introduction

```{r setup, eval = TRUE, echo = TRUE}
library(oneiric)
library(scater)
library(ggplot2)
library(RColorBrewer)
set.seed(288)
```

# Data

## Chaos Parameters
```{r chaos_param, eval = TRUE, echo  = TRUE}

data(oneiric)
map_params
```

## Simulated Territories
```{r sim_ter, eval = TRUE, echo = TRUE}
sim_ter <- paste0(system.file(package = "oneiric"), "/inst/extdata/")
dir(sim_ter)
```

## Preparing output directory

```{r out_dir, eval = TRUE, echo = TRUE}

output <- "/Users/martinp4/Documents/Cedars/Oneiric/simulations/"
```

# Creating New Data sets

## Territory Types

```{r spatial_sim, eval = TRUE, echo = TRUE}
circle <- simulate_spatial(n_cells = 5000,
    n_territories = 5,
    n_samples = 12,
    pattern = "circle",
    expanse = c(0.1, 0.3))

rod <- simulate_spatial(n_cells = 5000,
    n_territories = 5,
    n_samples = 12,
    pattern = "rod",
    width_range = c(0.0, 0.1),
    length_range = c(0.2, 0.5))

chaos_map <- simulate_spatial(n_cells = 5000,
    n_samples = 12,
    pattern = "chaos",
    expanse = 0.02)

layered_map <- simulate_spatial(n_cells = 5000,
    n_samples = 12,
    n_territories = 1,
    pattern = "circle",
    layers = 5,
    expanse =  c(0.4, 0.5))

```


```{r view_territory_types, eval = TRUE, echo = TRUE, fig.width = 9, fig.height=9, fig.cap = "Circular Territories"}
circles <- do.call("rbind", circle)
circles$Territory <- as.factor(circles$Territory)
cols <- colorRampPalette(RColorBrewer::brewer.pal(11, "Spectral"))
cols <- cols(length(levels(circles$Territory)))
g <- ggplot(circles, aes(x = x, y = y, col = Territory)) +
    geom_point(size = 0.5) +
    theme_bw() +
    scale_color_manual(values = cols) +
    facet_wrap(~sample) +
    guides(colour = guide_legend(
        override.aes = list(size =  5)))
print(g)

rods <- do.call("rbind", rod)
rods$Territory <- as.factor(rods$Territory)
cols <- colorRampPalette(RColorBrewer::brewer.pal(11, "Spectral"))
cols <- cols(length(levels(rods$Territory)))
g1 <- ggplot(rods, aes(x = x, y = y, col = Territory)) +
    geom_point(size = 0.5) +
    theme_bw() +
    scale_color_manual(values = cols) +
    facet_wrap(~sample) +
    guides(colour = guide_legend(
        override.aes = list(size =  5)))
print(g1)

tinker <- do.call("rbind", chaos_map)
tinker$Territory <- as.factor(tinker$Territory)
cols <- colorRampPalette(RColorBrewer::brewer.pal(11, "Spectral"))
cols <- cols(length(levels(tinker$Territory)))
g2 <- ggplot(tinker, aes(x = x, y = y, col = Territory)) +
    geom_point(size = 0.5) +
    theme_bw() +
    scale_color_manual(values = cols) +
    facet_wrap(~sample) +
    guides(colour = guide_legend(
        override.aes = list(size =  5)))
print(g2)

layers <- do.call("rbind", layered_map)
layers$Territory <- as.factor(layers$Territory)
cols <- colorRampPalette(RColorBrewer::brewer.pal(11, "Spectral"))
cols <- cols(length(levels(layers$Territory)))
g3 <- ggplot(layers, aes(x = x, y = y, col = Territory)) +
    geom_point(size = 0.5) +
    theme_bw() +
    scale_color_manual(values = cols) +
    facet_wrap(~sample) +
    guides(colour = guide_legend(
        override.aes = list(size =  5)))
print(g3)
```


## Simulating Circle data sets

```{r circle_solo, eval = TRUE, echo = TRUE}
# Making sure that we have common cell labels
circular <- simulate_spatial(n_cells = 5000,
    n_territories = 5,
    n_samples = 12,
    pattern = "circle",
    expanse = c(0.1, 0.25),
    force_cells = 10)

circular_counts <- simulate_cells(circular,
    cell_composition = 2)

circles <- do.call("rbind", circular_counts$spatial)
circles$Territory <- as.factor(circles$Territory)
cols <- colorRampPalette(RColorBrewer::brewer.pal(11, "Spectral"))
cols <- cols(length(levels(circles$Territory)))
g <- ggplot(circles, aes(x = x, y = y, col = Territory)) +
    geom_point(size = 0.5) +
    theme_bw() +
    scale_color_manual(values = cols) +
    facet_wrap(~sample) +
    guides(colour = guide_legend(
        override.aes = list(size =  5)))
print(g)


circles$cell_labels <- as.factor(circles$cell_labels)
cols <- colorRampPalette(RColorBrewer::brewer.pal(11, "Spectral"))
cols <- cols(length(levels(circles$cell_labels)))
g1 <- ggplot(circles, aes(x = x, y = y, col = cell_labels)) +
    geom_point(size = 0.5) +
    theme_bw() +
    scale_color_manual(values = cols) +
    facet_wrap(~sample) +
    guides(colour = guide_legend(
        override.aes = list(size =  5)))
print(g1)


export_simulation(spatial = circular_counts$spatial,
    cells = circular_counts$counts,
    out_dir = output,
    file_tag = "circle_spatial_territories")

```


## Simulating Layered Territories 

```{r circle_layer, eval = TRUE, echo = TRUE}
circular_layer <- simulate_spatial(n_cells = 5000,
    n_territories = 1,
    n_samples = 12,
    pattern = "circle",
    expanse = c(0.4, 0.5),
    layer = 5,
    force_cells = 12)

circular_layer_counts <- simulate_cells(circular_layer,
    as_layer = TRUE,
    cell_composition = 2)

circles <- do.call("rbind", circular_layer_counts$spatial)
circles$Territory <- as.factor(circles$Territory)
cols <- colorRampPalette(RColorBrewer::brewer.pal(11, "Spectral"))
cols <- cols(length(levels(circles$Territory)))
g <- ggplot(circles, aes(x = x, y = y, col = Territory)) +
    geom_point(size = 0.5) +
    theme_bw() +
    scale_color_manual(values = cols) +
    facet_wrap(~sample) +
    guides(colour = guide_legend(
        override.aes = list(size =  5)))
print(g)

circles$cell_labels <- as.factor(circles$cell_labels)
cols <- colorRampPalette(RColorBrewer::brewer.pal(11, "Spectral"))
cols <- cols(length(levels(circles$cell_labels)))
g <- ggplot(circles, aes(x = x, y = y, col = cell_labels)) +
    geom_point(size = 0.5) +
    theme_bw() +
    scale_color_manual(values = cols) +
    facet_wrap(~sample) +
    guides(colour = guide_legend(
        override.aes = list(size =  5)))
print(g)

export_simulation(spatial = circular_layer_counts$spatial,
    cells = circular_layer_counts$counts,
    out_dir = output,
    file_tag = "layered_spatial_territories")

```

### Circle Layers - NO Labels
```{r circle_layer_nl, eval = TRUE, echo = TRUE}
circular_layer_nl <- simulate_spatial(n_cells = 5000,
    n_territories = 1,
    n_samples = 12,
    pattern = "circle",
    expanse = c(0.4, 0.5),
    layer = 5,
    force_cells = 12)

circular_layer_counts_nl <- simulate_cells(circular_layer_nl,
    as_layer = TRUE,
    de_prob = 0.5,
    de_layer = 0.05,
    cell_composition = 2,
    no_label = TRUE)

# to mimic no cell type labels available

circles <- do.call("rbind", circular_layer_counts_nl$spatial)
circles$Territory <- as.factor(circles$Territory)
cols <- colorRampPalette(RColorBrewer::brewer.pal(11, "Spectral"))
cols <- cols(length(levels(circles$Territory)))
g <- ggplot(circles, aes(x = x, y = y, col = Territory)) +
    geom_point(size = 0.5) +
    theme_bw() +
    scale_color_manual(values = cols) +
    facet_wrap(~sample) +
    guides(colour = guide_legend(
        override.aes = list(size =  5)))
print(g)

circles$cell_labels <- as.factor(circles$cell_labels)
cols <- colorRampPalette(RColorBrewer::brewer.pal(11, "Spectral"))
cols <- cols(length(levels(circles$cell_labels)))
g <- ggplot(circles, aes(x = x, y = y, col = cell_labels)) +
    geom_point(size = 0.5) +
    theme_bw() +
    scale_color_manual(values = cols) +
    facet_wrap(~sample) +
    guides(colour = guide_legend(
        override.aes = list(size =  5)))
print(g)

export_simulation(spatial = circular_layer_counts_nl$spatial,
    cells = circular_layer_counts_nl$counts,
    out_dir = output,
    file_tag = "no_label_spatial_territories")

```
